### PR TITLE
[NetBSD] cmdline() can raise MemoryError

### PR DESCRIPTION
**Pull request by krytarowski**
* stop including `sys/user.h` for NetBSD
* Fix `psutil_get_cmd_args`

### CODE REVIEW

**Comment by giampaolo** [comment]
What was the problem with cmdline? It got truncated?

**Comment by krytarowski** [comment]
malloc(3) returned NULL for buffer of size with garbage

**Comment by iamleot** [comment]
Hello giampaolo,

giampaolo writes:
> What was the problem with cmdline? It got truncated? 

At least calling psutil.Process(pid).as_dict() lead to MemoryError,
e.g.:

 | % python3.7
 | Python 3.7.3 (default, May  3 2019, 17:54:14)
 | [GCC 7.4.0] on netbsd8
 | Type "help", "copyright", "credits" or "license" for more information.
 | >>> import psutil
 | >>> psutil.Process(1).as_dict()
 | Traceback (most recent call last):
 |   File "<stdin>", line 1, in <module>
 |   File "/usr/pkg/lib/python3.7/site-packages/psutil/__init__.py", line 638, in as_dict
 |     ret = meth()
 |   File "/usr/pkg/lib/python3.7/site-packages/psutil/__init__.py", line 790, in cmdline
 |     return self._proc.cmdline()
 |   File "/usr/pkg/lib/python3.7/site-packages/psutil/_psbsd.py", line 562, in wrapper
 |     return fun(self, *args, **kwargs)
 |   File "/usr/pkg/lib/python3.7/site-packages/psutil/_psbsd.py", line 666, in cmdline
 |     return cext.proc_cmdline(self.pid)
 | MemoryError

That was because in psutil_get_cmd_args() the kern.argmax sysctl(3)

    char *
    psutil_get_cmd_args(pid_t pid, size_t *argsize) {
        int mib[4];
        ssize_t st;
        size_t argmax;
        size_t size;
        char *procargs = NULL;
    
        mib[0] = CTL_KERN;
        mib[1] = KERN_ARGMAX;
    
        size = sizeof(argmax);
        st = sysctl(mib, 2, &argmax, &size, NULL, 0);
        if (st == -1) {
            PyErr_SetFromErrno(PyExc_OSError);
            return NULL;
    
        procargs = (char *)malloc(argmax);
        if (procargs == NULL) {
            PyErr_NoMemory();
            return NULL;
    
        [...]

Before calling sysctl() `size' was 8, after calling it `size' was 4.
However, later when calling `malloc(argmax)' `argmax' contained
uninitialized data and thus failing.

**Comment by krytarowski** [comment]
I plan to submit implementation of missing features for NetBSD, but I will do it with 1 PR after another.

**Comment by giampaolo** [comment]
Thanks, merged.

> I plan to submit implementation of missing features for NetBSD, but I will do it with 1 PR after another.

Sounds sweet. I am looking forward to that.

**Pull request merged**
