### PR TITLE
#1394 / win / exe: use QueryFullProcessImageNameW to get the exe()

### PR DESCRIPTION
**Pull request by giampaolo**
See #1394.

### CODE REVIEW

**Comment by giampaolo** [comment]
As said in https://github.com/giampaolo/psutil/issues/1394#issuecomment-464476034 this has the drawback of breaking backward compatibility on Win XP. I'm not sure how much time I'm willing to invest into this but roughly I see one solution:

1) use C pre-processor in order to identify the Windows version and choose the right code path:

```c
#if (_WIN32_WINNT >= 0x0600) // Windows Vista and above
   // new code using QueryFullProcessImageNameW
#else // Windows XP
    // old code using GetProcessImageFileNameW
#endif

2) implement a similar routine in the python code so that if WINVER < VISTA we use `QueryDosDevice` to convert the returned path in the right format

**Comment by giampaolo** [comment]
@ogurets if I land a patch including Win XP support could you please try (I have no Win XP box to test against)?

**Comment by ogurets** [comment]
@giampaolo Sure! Cannot promise I'll be swift though, I'm pretty piled up right now :(

**Comment by giampaolo** [comment]
No problem. In general terms this is low-priority anyway (I was tempted to remove Win XP support, but sort of felt a bit cautious... =)).

**Pull request merged**
