### PR TITLE
fix invokation of windows processes, so we can terminate() them 

### PR DESCRIPTION
**Pull request by dothebart**
one by one without shooting ourselves.

this takes care of:
https://github.com/giampaolo/psutil/issues/1737

### CODE REVIEW

**Comment by giampaolo** [comment]
I thought you were talking about the test suite. Here you're touching psutil itself. The point of `terminate()` method is being able to terminate *any* process, not only the ones created with the CREATE_NEW_PROCESS_GROUP flag. If that is your goal you should do it in your own code, registering your own signal handler. Doing so in a general purpose lib is not a good idea.

**Comment by dothebart** [comment]
it will continue to be able to terminate *any* process. However, if you *SPAWN* them without, it will continue to kill all processes you spawned. 

In the current implementation state psutils will simply allways *hard-kill* processes on windows *allways* which to that regard is way worse!

**Comment by giampaolo** [comment]
`psutil.Process` class can be used with any PID. In this PR you are registering a signal handler and using `exit()`. Both of those things affect the current process (`os.getpid()`), not the PID/process the `Process` instance is referring to.

**Comment by dothebart** [comment]
since its only registered for SIGINT this case shouldn't happen? Whats would be a better way to do this?

**Comment by giampaolo** [comment]
You mean avoid killing the entire group of process/PID you did NOT spawn? I don't know. But it seems to me your use case is about the processes created by yourself (os.getpid()), so you already have a solution. You have all the bits already, so just use it in your own code. =)

To fully recap, changing `Process.terminate()` the way you propose is a no-go because:
- it does not apply to any PID, just os.getpid() 
- it register a signal handler
- it would change the semantic of `Process.terminate()`, which should be the same as `subprocess.Popen.terminate()`, which is calling `TerminateProcess` Windows API

With that said, I agree that having something more high level (like a parameter to pass to `terminate()` or something) to avoid killing the entire process group (of any PID), would be nice to have, but as of now I can't say I understand the problem well enough to have a solid solution.

**Comment by dothebart** [comment]
the problem is, with whoever is spawning processes without using CREATE_NEW_PROCESS_GROUP will have a sigint sent to all processes in that group - be they parented from you or not. 
Thus you cannot soft-kill (signal to terminate with a regular shutdown) single processes of a group alone. 

Ok, I will have to fork psutils then and stop taking the work to do PRs.

**Pull request closed without merging**
