### PR TITLE
[Linux] Properly raise ZombieProcess in exe() method

### PR DESCRIPTION
**Pull request by Jongy**
## Summary

* OS: Linux
* Bug fix: yes
* Type: core
* Fixes: None

## Description
`psutil.Process(pid).exe()` returns `""` for zombie processes, incorrectly. It should raise `ZombieProcess`, and return `""` only for kernel threads.

This PR fixes the logic (I wrote something quick, I suppose that the logic can be reordered more nicely maybe).

Now we get:
* Alive processes - their `exe`
* Non-existing PIDs - `NoSuchProcess`
* Kernel threads - `""`
* Zombie processes - `ZombieProcess`.

Tested on kernel 5.4.

Also fixed & improved the comment along the way.

### CODE REVIEW

**Comment by Jongy** [comment]
I will look into the failing test later today

**Comment by Jongy** [comment]
I looked into the test. The logic here is incorrect:
```
                # ...but if /proc/pid no longer exist we're supposed to treat
                # it as an alias for zombie process
                with mock.patch('psutil._pslinux.os.path.lexists',
                                return_value=False):
                    self.assertRaises(
                        psutil.ZombieProcess, psutil.Process().exe)
```

if `/proc/pid` no longer exists, it's not a zombies. Zombies have their `/proc/pid`. It's a zombie if `/exe` link is missing & `.status()` is `"zombie"`.

How should I fix the test? The `lexists` patch is relevant for `NoSuchProcess`, so I can change that, & add another mock for `status()` which makes it look like a zombie?

**Comment by giampaolo** [comment]
> psutil.Process(pid).exe() returns "" for zombie processes, incorrectly. It should raise ZombieProcess, and return "" only for kernel threads.

Mmm why are you saying so? Can you provide a test case?
We do have a unit test for zombie processes (and it passes on Linux):
https://github.com/giampaolo/psutil/blob/1da9f7928e79ecc127768e7a5bc4eb7f785f4513/psutil/tests/test_process.py#L1297
Also, if there really is a problem with zombie detection, then we also have a problem with other Process methods, not only `exe()`.

With that said, by looking at the Linux code I also suspect we're not detecting/handling zombie properly, because BSD and OSX implementations do something different, similar to what you're doing in this PR:
* OSX: https://github.com/giampaolo/psutil/blob/1da9f7928e79ecc127768e7a5bc4eb7f785f4513/psutil/_psosx.py#L331-L336
* BSD: https://github.com/giampaolo/psutil/blob/1da9f7928e79ecc127768e7a5bc4eb7f785f4513/psutil/_psbsd.py#L545-L550

**Comment by giampaolo** [comment]
OK, I see what you mean now. `exe()` returns an empty string and `test_zombie_process` is too relaxed and does not test this condition (assumes `""` is a legit return value).

**Comment by Jongy** [comment]
> OK, I see what you mean now. `exe()` returns an empty string and `test_zombie_process` is too relaxed and does not test this condition (assumes `""` is a legit return value).

Precisely :)

I'm available to work on the PR if you want any changes to get this merged.

**Comment by Jongy** [comment]
We're using a patched version to work around this bug:
```
def process_exe(process: psutil.Process) -> str:
    """
    psutil.Process(pid).exe() returns "" for zombie processes, incorrectly. It should raise ZombieProcess, and return ""
    only for kernel threads.

    See https://github.com/giampaolo/psutil/pull/2062
    """
    exe = process.exe()
    if exe == "":
        if is_process_zombie(process):
            raise psutil.ZombieProcess(process.pid)
        raise MissingExePath(process)
    return exe
```

I'd love to remove it and get back to mainline haha.

**Comment by giampaolo** [comment]
I'm afraid this may affect other methods other than `exe()` and requires a more generic solution.

**Comment by giampaolo** [comment]
As I suspected, it turns out the problem not only affects  process `exe()`. We have it also in `cmdline()` and `memory_maps()`. I created https://github.com/giampaolo/psutil/pull/2288 which fixes the problem in a more generic way, and also expands tests for zombie processes.

**Comment by Jongy** [comment]
> As I suspected, it turns out the problem not only affects process `exe()`. We have it also in `cmdline()` and `memory_maps()`. I created #2288 which fixes the problem in a more generic way, and also expands tests for zombie processes.

That's great! Thanks.

**Pull request closed without merging**
