### PR TITLE
Issue #1183: implement ppid_map for Linux

### PR DESCRIPTION
**Pull request by pitrou**
This makes Process.children() 3x faster when there are no children.

### CODE REVIEW

**Comment by pitrou** [comment]
Note that Process.children(recursive=True) doesn't really benefit as it still creates a Process instance for every process on the system.

**Comment by pitrou** [comment]
@giampaolo

**Comment by pitrou** [comment]
I've got a patch to also make `children(recursive=True)`. Should I push it in this PR or create a separate PR for it?

**Comment by giampaolo** [comment]
That won't work as it's Linux only. The change is much simpler: just define a `_ppid_map()` utility function in `__init__.py` which relies on the per-module `Process` class directly. That way all platforms can benefit from the speedup.

**Comment by pitrou** [comment]
> The change is much simpler: just define a _ppid_map() utility function in __init__.py which relies on the per-module Process class directly.

Not sure what you mean by that? The point here is to avoid Process instantiations when we're only interested in a couple of them at the end.

**Comment by giampaolo** [comment]
Instantiating "private" (e.g. look into _pslinux.py) `Process` classes should be cheap as they define `__slots__` (contrarily from the `Process` class in `__init__`).

**Comment by giampaolo** [comment]
https://github.com/giampaolo/psutil/pull/1185

**Pull request closed without merging**
