### PR TITLE
Correctly calculate CPU percentages on linux with guests

### PR DESCRIPTION
**Pull request by Foxlik**
Since guest is already included in user and guest_nice is included in nice, it got included twice in totals.

http://unix.stackexchange.com/questions/178045/proc-stat-is-guest-counted-into-user-time

Please doublecheck this, as I can test just on recent linux.

### CODE REVIEW

**Comment by giampaolo** [comment]
Uhm... good catch. I'm not completely certain the explanation given in that SO thread is correct though. The first message talks about times in `/proc/stat` (the **system-wide** CPU times) whereas who posted the first answer talks about `/proc/[pid]/stat`, which are **process times**.

**Comment by giampaolo** [comment]
I'm trying to find an official reference which states that `guest` and `guest_nice` in /proc/stats are already included in `user` time.

**Comment by Foxlik** [comment]
@giampaolo Good point. I think this is enough proof: https://github.com/torvalds/linux/blob/master/kernel/sched/cputime.c#L158

And for explanation see very last paragraph of https://lists.linuxfoundation.org/pipermail/virtualization/2009-August/013459.html

**Comment by giampaolo** [comment]
Thanks, that's enough. =)
After further investigation it seems we are also calculating the busy time wrong (and hence the percentage is wrong).
Right now it's done as `busy = total - idle` but according to htop (see [here](http://stackoverflow.com/questions/5514119/accurately-calculating-cpu-utilization-in-linux-using-proc-stat) and [here](https://github.com/hishamhm/htop/blob/8af4d9f453ffa2209e486418811f7652822951c6/linux/LinuxProcessList.c#L867)) it should be `busy = total - idle - iowait`.

To push this even further, I'm not sure whether we should adjust the guest time calculation only in `cpu_percent()` or also in `cpu_times()` (I mean subtracting the `guest` and `guest_nice` from `user` and `nice`).

**Comment by giampaolo** [comment]
This is now correctly fixed. Thanks for discovering the original issue. I had no idea the CPU percent related math was not 100% correct.

**Comment by Foxlik** [comment]
Great. Thanks!

**Pull request closed without merging**
