### PR TITLE
WIP: preliminary Haiku port

### PR DESCRIPTION
**Pull request by mmuman**
Still a lot to do but enough to get [glances running](https://twitter.com/mmu_man/status/1227746291490467842).

### CODE REVIEW

**Comment by giampaolo** [comment]
Mmm... I've never heard of this OS before. How much used is it? Honestly I'm not sure if it's worth it.

**Comment by mmuman** [comment]
Well, there are so many OSes out there, [Haiku](https://www.haiku-os.org/) is one of them. You'd probably have said this of Linux 15y ago btw.

**Comment by mmuman** [comment]
Just rebased, no new feature yet.

**Comment by giampaolo** [comment]
Looking back at this, I'm sorry but I'm gonna reject it. There's been no demand for Haiku, and overall it looks like a very niche OS. To give an idea, these are the current psutil's monthly download stats:

```
| System name                    |       Downloads |
|:------------------------------ | ---------------:|
| Linux                          |      11,084,549 |
| Windows                        |         790,397 |
| Darwin                         |         232,315 |
| FreeBSD                        |           3,499 |
| OS/390                         |              88 |
| AIX                            |              84 |
| SunOS                          |              74 |
| OpenBSD                        |              39 |
```

Considering OpenBSD as the most underused platform with 39 monthly downloads, I expect Haiku numbers would be close to zero. 

More in general: since all major and most known minor platforms are already supported, the bar for entry for adding a new exotic/niche platform at this point is very high. The technical debt [1] simply outweighs the benefits. A separate fork + a specific PYPI package would serve this task more effectively.

[1] new code in main core and unit tests, doc adjustments, occasional bug reports which will likely be stagnating, etc.

**Pull request closed without merging**
