### PR TITLE
24line can't excute

### PR DESCRIPTION
**Pull request by whoamishuaige**
my env is centos7.0,python2.7,psutil2.0.0，that couldn't excute 24line.so i change this line as this

### CODE REVIEW

**Comment by giampaolo** [comment]
I don't understand the difference. This:
```
        proc_name = psutil.Process(user.pid).name() if user.pid else ""
```
is supposed to do the same thing no? (get name() if user.pid is true)

**Comment by giampaolo** [comment]
Actually I realize that if user.pid is 0 for some reason that won't work.

**Comment by giampaolo** [comment]
Anyway, can you paste the traceback? Are you getting an `AttributeError`?

**Comment by whoamishuaige** [comment]
when i run python who.py,i get a AttributeError like this AttributeError: 'suser' object has no attribute 'pid'.so i want to know the what is python,for that i enter python terminal,excute the command like this import psutil;
psutil.users()
then i got result
[suser(name='root', terminal='pts/2', host='220.249.22.170', started=1517387776.0)]
so that pid is undefined in psutil.users object.my env is python 2.7.5,psutil is 2.0.0,os is centos7.x.

**Comment by giampaolo** [comment]
psutil 2.0.0 is ancient! You should upgrade it (we're at 5.4.3).

**Comment by whoamishuaige** [comment]
thank you,sloving this problem for me

**Comment by giampaolo** [comment]
To be precise:  =)
psutil-0.2.0: 2010-11-13
https://github.com/giampaolo/psutil/blob/master/HISTORY.rst#020

**Pull request closed without merging**
