### PR TITLE
feat: add aarch64 manylinux wheels

### LINKED ISSUE #1966: [Linux] Publish armv7l & aarch64 wheels
## Summary

* OS: Linux TurrisOS armv7l
* Type: wheels

## Description
Can you publish a wheel for armv7l?

Older RasPi’s, various embedded boards, OpenWRT routers are the things that could be supported, in addition to the x86_64 port already present

Reference:

https://github.community/t/create-matrix-with-multiple-os-and-env-for-each-one/16895

should also close giampaolo/psutil#1290

### LINKED ISSUE #1972: [Linux][aarch64] Wheel support for aarch64 Linux
## Summary

* OS: Linux aarch64
* Type: wheels

## Description

This is the same feature request as #1782. I would really love to see wheel support for aarch64, as AWS's Graviton ARM-based VMs are getting more popular. Making a wheel for aarch64 would help so many projects that depend on `psutil`.

### LINKED ISSUE #2206: ARM64 support
As mentioned in #1782 -- arm64 and it's variants (armv7, armv8, aarch64) are here to stay -- and likely in much higher usage these days with IoT (ie esp32, etc), Raspberry PIs and it's alternatives, and of course AWS with it's Graviton 2 & 3 processors (which have been steadily & rapidly growing in usage especially given higher performance and lower cost compared to their non-Graviton instance types).

Opening this request hoping that `psutil` will reconsider providing wheels for these types of processors. Many companies don't allow software such as gcc, devel packages, etc on production servers and so for many, including myself, it is impossible to deploy `psutil` into a production environment.

Given the high value of `psutil` and that it is often embedded into other packages (meaning you can't use alternatives), hopefully you will reconsider.

While I realize #1972 exists, this request is to support more then just the `aarch64` variant.

### LINKED ISSUE #2210: [Linux] What does it need to have IBM Power (ppc64le) support?
## Summary

Hello!

As people already indicated it is not difficult to build psutil for other CPU architectures like aarch64 or ppc64le, however many other projects rely on psutil and therefore I'd like to understand what exactly is needed from your side to support these architectures?

I understand your concerns you've shared in [#2103](https://github.com/giampaolo/psutil/pull/2103#issuecomment-1252720051) that there'll be too much additional effort from your side, but would it be an option to introduce platform support based on different Tiers, similar as done in the Qiskit Package (https://qiskit.org/documentation/getting_started.html#platform-support)?

There the basic distinction is:
- T1: Wheels are built, tested & uploaded to pypi, fully tested upstream during development and have all dependencies available, ensuring easy installation.
- T2: Wheels are built, tested & uploaded to pypi, not tested upstream but binaries are available for easy installation.
- T3: Wheels are built & uploaded to pypi, but not tested and it is not ensured to install without further effort.

Furhtermore, would it be helpful if we (IBM) support you in maintaining and reviewing issues & PRs related (but not limited) to e.g. ppc64le wheels?

I'd appreciate your view on that!

### PR DESCRIPTION
**Pull request by mayeut**
## Summary

* OS: Linux
* Bug fix: no
* Type: wheels
* Fixes:
fixes #1966
fixes #1972
fixes #2206
mitigates #2090
mitigates #2175
mitigates #2293
closes #2178
closes #2224

## Description

This PR continues work from #2103 (I've never removed that branch and rebased on master once in a while so that's the same branch  in this PR).

cherry-picked commits from #2126 for missing test dependency in manylinux.

main differences between this PR and #2224:
- This PR does not build `ppc64le` & `s390x`.
- This PR does not build musllinux wheels.
- This PR adds tests for architectures running QEMU:
While the tests needed some modifications in order to pass, IMHO, it's best to check than what can be tested does work as intended.
Running with QEMU however hides some bugs (thinking about /proc/cpuinfo and cpu related stuff here) that actually do exist or comes with its own bugs (s390x and /proc endianness issue is most likely a qemu issue).
aarch64 will most likely be able to run natively [by the end of the year](https://github.blog/2024-06-03-arm64-on-github-actions-powering-faster-more-efficient-build-systems/).

- This PR does not add Windows ARM64 wheel
It could be added without any tests but I'd rather see Microsoft add Windows ARM64 runners to GitHub if they want to get some traction for their new platform (hopefully [by the end of the year](https://github.blog/2024-06-03-arm64-on-github-actions-powering-faster-more-efficient-build-systems/)).

- This PR does not add macOS universal2 wheel
My personal opinion is that it's not useful as long as you provide both x86_64 & arm64 wheels (which is the case).
They do take more space for the end user, pip will always choose the most specific one so publishing 3 will change nothing for almost all users. Remain people packaging universal2 python apps, and, IMHO, this should be handled by the tools creating such apps.

- This PR feels simpler regarding the change of workflow

Regarding tests that are failing on real arm64 hardware but hidden by QEMU testing:
- Using docker on macOS M1:
```
======================================================================
FAIL: psutil.tests.test_system.TestCpuAPIs.test_cpu_freq
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/project/psutil/tests/test_system.py", line 609, in test_cpu_freq
    assert ls, ls
AssertionError: []

======================================================================
FAIL: psutil.tests.test_linux.TestSystemCPUCountCores.test_method_2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/project/psutil/tests/test_linux.py", line 820, in test_method_2
    self.assertEqual(meth_1, meth_2)
AssertionError: 10 != None

======================================================================
FAIL: psutil.tests.test_linux.TestSystemCPUFrequency.test_emulate_use_second_file
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/project/psutil/tests/test_linux.py", line 845, in test_emulate_use_second_file
    assert psutil.cpu_freq()
AssertionError

======================================================================
FAIL: psutil.tests.test_linux.TestSystemNetIfAddrs.test_ips
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/project/psutil/tests/test_linux.py", line 1020, in test_ips
    self.assertEqual(addr.address, get_mac_address(name))
AssertionError: '00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00' != '00:00:00:00:00:00'
- 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
+ 00:00:00:00:00:00
```
- Using [CirrusCI](https://cirrus-ci.com/task/5366593759215616) (Neoverse-N1):
```
======================================================================
FAIL: psutil.tests.test_system.TestCpuAPIs.test_cpu_freq
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/project/psutil/tests/test_system.py", line 609, in test_cpu_freq
    assert ls, ls
AssertionError: []
======================================================================
FAIL: psutil.tests.test_system.TestSensorsAPIs.test_sensors_temperatures
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/project/psutil/tests/test_system.py", line 942, in test_sensors_temperatures
    self.assertGreaterEqual(entry.high, 0)
AssertionError: -273.15 not greater than or equal to 0
======================================================================
FAIL: psutil.tests.test_linux.TestSystemCPUCountCores.test_method_2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/project/psutil/tests/test_linux.py", line 820, in test_method_2
    self.assertEqual(meth_1, meth_2)
AssertionError: 4 != None
======================================================================
FAIL: psutil.tests.test_linux.TestSystemCPUFrequency.test_emulate_use_second_file
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/project/psutil/tests/test_linux.py", line 845, in test_emulate_use_second_file
    assert psutil.cpu_freq()
AssertionError
```

### CODE REVIEW

**Comment by giampaolo** [comment]
Thank you Matthieu. 

> I added other platforms as well (ppc64le & s390x) [...] and musllinux 

Please, let's just add aarch64 wheels for now (the ones with the highest demand). There's too many `skipIf(...)` which seems are due to emulation. Just so you know: my main concern here is keeping things as simple and maintainable as possible. Above all, we shouldn't introduce new random test failures (we already have a lot), and producing wheels / releases should be a smooth process.

**Comment by mayeut** [comment]
> Please, let's just add aarch64 wheels for now (the ones with the highest demand)

I removed `ppc64le` & `s390x` (there's one demand from IBM #2210 for ppc64le).


I kept musllinux which are I think the second highest demand with 1 related issue & 3 opened PR).
If you don't want to keep musllinux, just drop the commit [445b35d](https://github.com/giampaolo/psutil/pull/2425/commits/445b35d2b6d917d990043b05663904d6715d4635).
Please note that [6f55304](https://github.com/giampaolo/psutil/pull/2425/commits/6f55304a6bdb46968cae41949cb82071bb414aae) is related to the addition of musllinux which comes with an up-to-date version of `free`/`vmstat`. Even if not building musllinux, this one will eventually come back as an issue once glibc distros get updated.


> There's too many skipIf(...) which seems are due to emulation. Just so you know: my main concern here is keeping things as simple and maintainable as possible.

There are now less with s390x being dropped. I however understand your concern. Given GHA will most likely provide a native aarch64 before the end of the year, the test commit might be dropped completely [6aa80d3](https://github.com/giampaolo/psutil/pull/2425/commits/6aa80d33f7c05c2f3a0f1e8ad48b15e2f0215039).

> Above all, we shouldn't introduce new random test failures (we already have a lot), and producing wheels / releases should be a smooth process.

Agreed, that's why I disabled test_memleaks on those architectures. It was the only flaky one as far as I saw (and memleaks should mostly be independent of the processor architecture and tested otherwise).

Please feel free to force-push, drop commits, ... as you see fit. I have backups / alternatives to this work in my fork.

**Comment by giampaolo** [comment]
> If you don't want to keep musllinux, just drop the commit [445b35d](https://github.com/giampaolo/psutil/pull/2425/commits/445b35d2b6d917d990043b05663904d6715d4635).

It seems I cannot modify your PR (I can push but can't see the changes reflected in here).
Can you please remove musl wheels and update the README? The rest looks good.
Also one minor thing. Is there a reason why it's called `QEMU_USER` instead of `QEMU`?

**Comment by mayeut** [comment]
> It seems I cannot modify your PR (I can push but can't see the changes reflected in here).

weird...
anyway

> Also one minor thing. Is there a reason why it's called QEMU_USER instead of QEMU?

QEMU provides full-system emulation or user-mode emulation. Here, we only use user-mode emulation.

**Comment by mayeut** [comment]
> update the README?

I guess you meant HISTORY ?

**Comment by giampaolo** [comment]
Yes, sorry. 😄

**Pull request merged**
