### PR TITLE
Add inet_ntop support for WinXP and IPv4/v6

### LINKED ISSUE #638: DLL load failed - cx_freeze
I get the following stacktrace when I try to start a program using the 3.0.1 psutil library.
The program is packed using cx_freeze on a Windows 7 machine and gets executed on a Windows XP machine.
The problem does not occur on psutil 2.2.1

    Traceback (most recent call last):
      File "C:\Python27\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
      File "main.py", line 6, in <module>
      File "C:\Python27\lib\site-packages\psutil\__init__.py", line 110, in <module>
      File "C:\Python27\lib\site-packages\psutil\_pswindows.py", line 16, in <module>
      File "ExtensionLoader_psutil__psutil_windows.py", line 22, in <module>
      File "ExtensionLoader_psutil__psutil_windows.py", line 14, in __bootstrap__
    ImportError: DLL load failed: Die angegebene Prozedur wurde nicht gefunden.

### PR DESCRIPTION
**Pull request by mrjefftang**
Fixes #638

### CODE REVIEW

**Comment by mrjefftang** [comment]
Turns out the issue in #616 was that I didn't have IPv6 enabled on my test VMs there for the inet_ntop() function only supported IPv4.

**Comment by giampaolo** [comment]
What happens on XP without this change?

**Comment by mrjefftang** [comment]
You get the DLL load failed that was identified in #638 .  The issue is that WinXP doesn't have `inet_ntop()` so we have to reimplement it in order for `psutil.net_if_addrs()` to work.

**Comment by giampaolo** [comment]
Ah yes, cool. Please update HISTORY / CREDITS as usual and this is good to go.
And thanks. =)

**Comment by mrjefftang** [comment]
Done

**Pull request merged**
