### PR TITLE
Use PAGE_SIZE macro instead of getpagesize() for macOS.

### PR DESCRIPTION
**Pull request by doneria-anjali**
For issue 1791 (https://github.com/giampaolo/psutil/issues/1791)

### CODE REVIEW

**Comment by kainjow** [comment]
@doneria-anjali `PAGE_SIZE` value is only known at compile time, while Apple Silicon needs to know this at runtime.

Can you try just adding `#include <unistd.h>`? This function should still be available AFAIK.

**Comment by kainjow** [comment]
I confirmed the include is all you need with this little hack:

```sh
echo "#include <unistd.h>" > /tmp/test.h
CFLAGS="-include /tmp/test.h" pip install psutil
```

**Comment by doneria-anjali** [comment]
It works! Thanks for the help Kevin.

Without this little hack, it gives error. Shall I change the use of PAGE_SIZE to something else that works both compile time and runtime?

**Comment by doneria-anjali** [comment]
A friendly ping to follow up on this pull request. Thanks!

**Comment by giampaolo** [comment]
Hello. I currently don't have an OSX box to test against, but this error:

```
ImportError: dynamic module does not define init function (init_psutil_osx)
```

...seems unrelated by the introduction of `#include <unistd.h>`. Are you sure you didn't change something else or you accidentally messed up psutil installation? In this case (messed up psutil installation) I suggest to run `make uninstall` (a couple of times) and `make clean` first, then retry.
It seems to me using `#include <unistd.h>` + `getpagesize()` should be the way to go, because:
1) it is documented by Apple:
https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/getpagesize.3.html
2) it is being used by cPython's `resource.getpagesize()`: https://github.com/python/cpython/blob/master/Modules/resource.c#L309-L325
3) in the unlikely event the OS/user changes the default page size, `getpagesize()` syscall is supposed to return an updated result, while `PAGE_SIZE` macro will not

Hope this helps.

**Comment by giampaolo** [comment]
> In this case (messed up psutil installation) I suggest to run make uninstall (a couple of times) and make clean first, then retry.

Note: by default python3 will be used, so if you're on python 2 you actually want this instead:

```
make uninstall PYTHON=python
make uninstall PYTHON=python
make clean PYTHON=python
```

**Comment by ThiagoIze** [comment]
I can also confirm that adding `#include <unistd.h>` fixes the build. Can we have that committed please?

**Comment by giampaolo** [comment]
I proceeded by adding `#include <unistd.h>`. If this didn't work please reopen #1791.

**Pull request closed without merging**
