### PR TITLE
fix compiler error for MSVC2015 (unscoped enum C++11 problem)

### PR DESCRIPTION
**Pull request by msarahan**
Tested on Py2.7 (MSVC2008) and Py3.5(MSVC2015)

### CODE REVIEW

**Comment by AcidWeb** [comment]
:+1:

**Comment by giampaolo** [comment]
Please update also HISTORY + CREDITS then it's good to go.

**Comment by msarahan** [comment]
Thanks for merging this.  It occurred to me recently that it's not the MSVC version that matters, but rather the MS SDK version that is in use.  I will submit a separate PR for this issue.

**Comment by msarahan** [comment]
Gah, scratch that, it's really actually BOTH: VS2013 and up enforce the unscoped enum rule of C++11, but there's only an unscoped enum problem for newer versions of the MS SDK (I believe Win 10+).

Any opinion on whether this is worth further work?

**Comment by giampaolo** [comment]
I personally don't understand the issue so I am not sure what to recommend.
Do you think we should revert your change?
Il 14/ott/2015 15:12, "Mike Sarahan" <notifications@github.com> ha scritto:

**Comment by msarahan** [comment]
This is certainly not worth reverting.  This is still a fix for the most
common configurations that anyone will have.  However, there is an edge
case that I worry a little bit about, and don't understand the implications
of:

If psutil is compiled with VS >= 2013, using MS SDK < 10, then
ProcessBreakOnTermination
will not be defined in that enum.

The MS SDK version I'm not completely certain about. ProcessBreakOnTermination
is not defined in Win 7 SDK, but is in 10. I don't know about Win 8 SDK.

**Comment by upsuper** [comment]
AFAICS, it starts existing from Win 8.1 SDK.

I'm seeing this issue:
```
 0:16.12 C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DPSUTIL_VERSION=330 -D_WIN32_WINNT=0x0602 -D_AVAIL_WINVER_=0x0602 -D_CRT_SECURE_NO_WARNINGS -DPSAPI_VERSION=1 -Ic:\mozilla-build\python\include -Ic:\mozilla-source\central\obj-firefox-opt\_virtualenv\PC /Tcpsutil/_psutil_windows.c /Fobuild\temp.win32-2.7\Release\psutil/_psutil_windows.obj
 0:16.13
 0:16.13 _psutil_windows.c
 0:16.13
 0:16.14 central\python\psutil\psutil\arch\windows\ntextapi.h(214) : error C2365: 'ProcessBreakOnTermination' : redefinition; previous definition was 'enumerator'
 0:16.15
 0:16.16         C:\Program Files (x86)\Windows Kits\10\include\10.0.10586.0\um\winternl.h(308) : see declaration of 'ProcessBreakOnTermination'
 0:16.16
 0:16.17 central\python\psutil\psutil\arch\windows\ntextapi.h(214) : error C2086: '_PROCESSINFOCLASS2 ProcessBreakOnTermination' : redefinition
 0:16.17
 0:16.18         central\python\psutil\psutil\arch\windows\ntextapi.h(214) : see declaration of 'ProcessBreakOnTermination'
 0:16.18
 0:16.19 Warning: C4028 in central\python\psutil\psutil\arch\windows\inet_ntop.h: formal parameter 2 different from declaration
 0:16.19 central\python\psutil\psutil\arch/windows/inet_ntop.h(10) : warning C4028: formal parameter 2 different from declaration
 0:16.20
 0:16.20 psutil/_psutil_windows.c(3065) : warning C4133: 'function' : incompatible types - from 'PyObject *' to 'const char *'
 0:16.21
 0:16.22 error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 11.0\\VC\\BIN\\cl.exe' failed with exit status 2
```

Not sure why it uses compiler from VC11...

**Comment by upsuper** [comment]
OK so it seems because Python 2.7.x is built with VS2008, so our (Mozilla) build system tries to use the earliest version of VC it can find to minimize the difference, which happens to be VC11 on my machine.

So I guess we should make the condition SDK-aware instead of compiler-aware.

**Comment by upsuper** [comment]
Following instructions inside to install a VC2008 Express makes everything work.

**Pull request merged**
