### PR TITLE
Implement inet_ntop to support Windows XP

### PR DESCRIPTION
**Pull request by mrjefftang**
Fixes the issue I found @ https://github.com/giampaolo/psutil/pull/597#issuecomment-92452682

### CODE REVIEW

**Comment by giampaolo** [comment]
Sorry for getting at this so late. I don't like having a new file for this. Do you think it's possible to do this in `psutil/_psutil_windows.c`?

**Comment by mrjefftang** [comment]
It's possible but _psutil_windows.c seems to be focused on adding actual functionality where as this is just adding a missing library function for Windows XP.  It'd be a lot easier to drop in the future (once XP support is removed) if it's kept in a separate file.

**Comment by giampaolo** [comment]
I see your point. OK then. Can you please update HISTORY and CREDITS as well? Then we can merge.

**Comment by mrjefftang** [comment]
Done and rebased.

**Comment by giampaolo** [comment]
Merged. Thanks.

**Comment by giampaolo** [comment]
After this change I get 2 errors on Windows 7:

```
test_special_pid (_windows.WindowsSpecificTestCase) ... ok
test_total_phymem (_windows.WindowsSpecificTestCase) ... ok

======================================================================
ERROR: test_net_if_addrs (__main__.TestSystemAPIs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test\test_psutil.py", line 986, in test_net_if_addrs
    nics = psutil.net_if_addrs()
  File "C:\Python27\lib\site-packages\psutil-3.0.0-py2.7-win32.egg\psutil\__init__.py", line 1763, in net_if_addrs
    rawlist = _psplatform.net_if_addrs()
WindowsError: [Error 10014] The system detected an invalid pointer address in attempting to use a pointer argument in a call

======================================================================
ERROR: test_ifconfig (__main__.TestExampleScripts)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test\test_psutil.py", line 2730, in test_ifconfig
    self.assert_stdout('ifconfig.py')
  File "test\test_psutil.py", line 2679, in assert_stdout
    out = sh(sys.executable + ' ' + exe).strip()
  File "test\test_psutil.py", line 192, in sh
    raise RuntimeError(stderr)
RuntimeError: Traceback (most recent call last):
  File "C:\cygwin64\home\user\psutil\examples\ifconfig.py", line 78, in <module>
    main()
  File "C:\cygwin64\home\user\psutil\examples\ifconfig.py", line 60, in main
    for nic, addrs in psutil.net_if_addrs().items():
  File "C:\Python27\lib\site-packages\psutil-3.0.0-py2.7-win32.egg\psutil\__init__.py", line 1763, in net_if_addrs
    rawlist = _psplatform.net_if_addrs()
WindowsError: [Error 10014] The system detected an invalid pointer address in attempting to use a pointer argument in a call


----------------------------------------------------------------------
```

**Pull request merged**
