### PR TITLE
Make uptime type consitent to fix boot time error.

### PR DESCRIPTION
**Pull request by xiaolingbao**
https://github.com/giampaolo/psutil/issues/1223

### CODE REVIEW

**Comment by giampaolo** [comment]
The downside of this is that psutil cannot be compiled on Windows < Vista. Can you leave the pre-processor stuff in place?

**Comment by xiaolingbao** [comment]
Thanks for your comment. Sorry I don't have system < Vista at the moment and I cannot see where is the offending line in the change. Can you please paste the compile error if possible?

**Comment by giampaolo** [comment]
I also don't have < Vista but last time I checked (maybe 1 year ago) psutil could be compiled from sources on Windows XP. If possible I would like to keep it that way.

**Comment by xiaolingbao** [comment]
I reviewed the code several times and I think it should still compile, unless I missed something :)
The conditional compile seems unnecessary. I'll try to find a system < vista to try later. Thank you again.

**Comment by giampaolo** [comment]
`ULONGLONG` does not exist on < Vista so as it stands it should not compile.

**Pull request merged**
