### PR TITLE
test_cpu_count: fix dependency on /proc/cpuinfo

### PR DESCRIPTION
**Pull request by grobian**
Fixes issue #620

### CODE REVIEW

**Comment by giampaolo** [comment]
There's no need to update HISTORY.rst for this.

**Comment by wiggin15** [comment]
Hi, I just wanted to mention that there's a fix for this (and other tests on Solaris) in #610.

**Comment by grobian** [comment]
that would be 5c28b2b16f3a1fcc4683d21d762504d85dfa79e7

**Comment by giampaolo** [comment]
This is supposed to have been fixed by #610.

**Pull request closed without merging**
