### PR TITLE
cpu_times() GetSystemTimes function double dword convert to __int64,t…

### PR DESCRIPTION
**Pull request by stswandering**
cpu_times() GetSystemTimes function double dword convert to __int64,then double,instead of float.

### CODE REVIEW

**Comment by giampaolo** [comment]
So, I took those "weird" numbers from cPython source code (`os.times()` function):
https://github.com/python/cpython/blob/3b20d3454e8082e07dba93617793de5dc9237828/Modules/posixmodule.c#L7734
As such, I would kinda feel safer if we leave them in place instead of introducing a new conversion logic.
What happens if simply cast the numbers to `double`?
Something like (pseudo code):

```c
        user = (float)((HI_T * sppi[i].UserTime.HighPart) +
                       (LO_T * sppi[i].UserTime.LowPart));
        ...
        Py_BuildValue("d", user);
```

**Comment by stswandering** [comment]
Cool! I have tried this method,it returns the same value. So, I change my pull request.

**Comment by giampaolo** [comment]
You also need to change this:
```
Py_BuildValue("(fff)", user, system, idle);
```
...to this:
```
Py_BuildValue("(ddd)", user, system, idle);
```

**Comment by stswandering** [comment]
Yeah,Sure! It's my fault.

**Comment by giampaolo** [comment]
LGTM. Merging. Thanks. ;)

**Pull request merged**
