### PR TITLE
swap_memory() tries /proc/stat if /proc/vmstat missing

### PR DESCRIPTION
**Pull request by dpavlenkov**
In joyent's SmartOS LX-brand zones, /proc/vmstat is missing but /proc/stat is available.

### CODE REVIEW

**Comment by giampaolo** [comment]
Mmmm.. on Ubuntu 14.04 that's not available:

```
~/svn/psutil {master}$ cat /proc/stat | grep swap
~/svn/psutil {master}$
```

**Comment by dpavlenkov** [comment]
/proc/stat -> swap is available in Joyent's LX zones. On real ubuntu /proc/vmstat is available. This doesn't affect real linux behavior, but it fixes LX zones.

**Comment by giampaolo** [comment]
I guess I'm completely ignorant about this SmartOS / LX zones. Can you elaborate what this patch is trying to fix/address and on what operating systems?

**Comment by dpavlenkov** [comment]
https://docs.joyent.com/public-cloud/instances/infrastructure/images
https://wiki.smartos.org/display/DOC/LX+Branded+Zones

Lx branded zones are linux containers on illumos. They should work like native linux, but that's work in progress. Some features are missing like /proc/vmstat . So, at first swap_memory barfed. You fixed that. Now this PR is about getting useful numbers for sin sout. They are available in /proc/stat.

**Comment by dpavlenkov** [comment]
Let's hold this thought. I haven't seen non-zero values for sin/sout. If I can't get numbers, then this patch is moot.

**Comment by dpavlenkov** [comment]
Closing PR because swap in/out are not available on this platform.

**Pull request closed without merging**
