### PR TITLE
convert mach tick units to nsecs

### LINKED ISSUE #1956: [macOS / M1] cpu_percent() gives incorrect information
## Summary

* OS: macOS 11.4
* Architecture: ARM
* Psutil version: 5.8.0
* Python version: 3.9.4
* Type: core

## Description

Process.cpu_percent() always reports very low cpu usage, in contradiction to top and Activity monitor. This test program:

```
from concurrent.futures import ThreadPoolExecutor
import psutil
import time
from math import log

def work(n):
    m = 0
    for i in range(1, n**2):
        m += log(i)
    return True
    
executor = ThreadPoolExecutor(max_workers=2)
task = executor.submit(work, 10000)

proc = psutil.Process()
while not task.done():
    print(proc.cpu_percent(interval=1))
```

consistently reports 2.4% usage on the Mac (vs. ~100% usage, as expected, on linux with the same version of psutil).

### PR DESCRIPTION
**Pull request by rmalouf**
## Summary

* OS: macOS 11.4
* Bug fix: yes
* Type: core
* Fixes: #1956, nicolargo/glances#1827

## Description

{{{
Mach sys calls report cpu time in "tick units" -- on intel cpus, these happen to be nsecs but on M1 machines they're about 40 nsecs. This PR corrects for this, but I think it still needs two improvements: the value of mach_timebase_info should be cached somewhere, and there are probably other places where the code depends on 1 tick=1 nsec that also need to be updated. Sounds reasonable? I can work on both of those, but I wanted to get some feedback first before I spend any more time on this.
}}}

### CODE REVIEW

**Comment by giampaolo** [comment]
Shouldn't this be executed on M1 only (`if M1 {do_this} else {do_old_stuff})`?

**Comment by rmalouf** [comment]
No, that's not necessary: mach_timebase_info will always give you a valid conversion factor, even if it happens to be 1/1.

**Comment by giampaolo** [comment]
(closing & reopening to trigger a CI test run)

**Comment by giampaolo** [comment]
(closing & reopening to trigger a CI test run)

**Comment by giampaolo** [comment]
@rmalouf looks like there are compilation issues:

```
2021-10-02T09:27:47.8665360Z   psutil/_psutil_osx.c:224:25: error: use of undeclared identifier 'info'; did you mean 'sinf'?
2021-10-02T09:27:47.8666080Z       mach_timebase_info(&info);
2021-10-02T09:27:47.8666510Z                           ^~~~
2021-10-02T09:27:47.8666870Z                           sinf
2021-10-02T09:27:47.8668040Z   /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/math.h:328:14: note: 'sinf' declared here
2021-10-02T09:27:47.8668860Z   extern float sinf(float);
2021-10-02T09:27:47.8669250Z                ^
2021-10-02T09:27:47.8670190Z   psutil/_psutil_osx.c:225:39: error: use of undeclared identifier 'info'
2021-10-02T09:27:47.8670860Z       total_user = pti.pti_total_user * info.numer;
2021-10-02T09:27:47.8671370Z                                         ^
2021-10-02T09:27:47.8672280Z   psutil/_psutil_osx.c:226:19: error: use of undeclared identifier 'info'
2021-10-02T09:27:47.8672930Z       total_user /= info.denom;
2021-10-02T09:27:47.8673330Z                     ^
2021-10-02T09:27:47.8674210Z   psutil/_psutil_osx.c:227:43: error: use of undeclared identifier 'info'
2021-10-02T09:27:47.8675150Z       total_system = pti.pti_total_system * info.numer;
2021-10-02T09:27:47.8675680Z                                             ^
2021-10-02T09:27:47.8676670Z   psutil/_psutil_osx.c:228:21: error: use of undeclared identifier 'info'
2021-10-02T09:27:47.8677690Z       total_system /= info.denom;
2021-10-02T09:27:47.8678100Z                       ^
2021-10-02T09:27:47.8678490Z   5 errors generated.
2021-10-02T09:27:47.8679390Z   error: command 'gcc' failed with exit status 1
```

**Comment by odormond** [comment]
> I have only tested it on Intel mac yet but will give it a shot tomorrow on M1.

I finally managed to get my hands on an M1 and I can now confirm that this works.

I've tested it on intel Monterey with python 3.9.6 from brew and M1 BigSur with python 3.8.2 from Apple.

**Comment by giampaolo** [comment]
Please open a PR. Just make sure that adding `struct mach_timebase_info info;` does not break anything on non-M1 systems (but unit tests run by GitHub should tell us that).

**Comment by giampaolo** [comment]
Closing this out since it's been outdated / fixed by https://github.com/giampaolo/psutil/pull/2011.

**Pull request closed without merging**
