### PR TITLE
Openbsd support (#562)

### PR DESCRIPTION
**Pull request by landryb**
Isnt perfect yet, but would be nice to merge early so that the work isnt lost. Basic functionality needed by end users work...

### CODE REVIEW

**Comment by benoitc** [comment]
+1

**Comment by giampaolo** [comment]
I took a look back at this and updated code:
https://github.com/giampaolo/psutil/tree/landryb-openbsd
What's missing:
- `Process.memory_info().vms` (aka `kp.p_vm_map_size`) is always 0. "ps" manages to show VMS somehow; as a last resort we might parse ps output.
- `Process.open_files()`'s path is an empty string; `kif->f_mntonname` refers to the mountpoint (useless), `kif->unp_path` is always empty. `lsof` somehow manages to do it.
- `Process.cwd()` is not implemented; couldn't find any way to determine this. `lsof` somehow manages to get this.
- `Process.memory_maps()` is not implemented.
- `Process.threads()` returns EINVAL.
- `Process.connetions()` and `net_connections()`'s `status` is always `None`
- `Process.connetions()` and `net_connections()`'s `addr` is always `None` for IPv6 sockets.
- `Process.cmdline()` does not return the actual cmdline; we get things such as `['pflogd: [running] -s 160 -i pflog0 -f /var/log/pflog']`, `['sshd: user@notty']` and `['smtpd: scheduler']`.
- `Process.num_ctx_switches()`'s `involuntary` field is always `0`; I suppose this means it is just not supported on OpenBSD so it's OK to skip this test.

**Comment by giampaolo** [comment]
`Process.cwd()` implemented in https://github.com/giampaolo/psutil/commit/04102058124bc41a0630a5d6e5d8f22eb035e26d

**Comment by giampaolo** [comment]
Process vms fixed in https://github.com/giampaolo/psutil/commit/eeac17f3b01bd82c61a3067558a2e559ba358ba6.

**Comment by giampaolo** [comment]
Process threads() implemented in https://github.com/giampaolo/psutil/commit/67da39e5e7b6e6ecd8ceef00db6f028ffd3ce6e1.

**Comment by giampaolo** [comment]
Process `num_threads()` implemented in https://github.com/giampaolo/psutil/commit/2ce156bc2540598a91e9c311eb1d553143d7b3aa.

**Comment by landryb** [comment]
Thanks for picking up this, i admit it feel out of the radar since i had no time for it...

**Comment by giampaolo** [comment]
OK, I merged everything in here: https://github.com/giampaolo/psutil/pull/709
Last remaining issues are:
- `Process.memory_maps()` is not supported
- `Process.open_files()` return empty paths (also FreeBSD has this problem)
- `Process.exe()` is not fully implemented and currently relies on `cmdline()`

**Comment by landryb** [comment]
as i already said several times, open_files() will never get implemented, the kernel won't provide such an API.

**Comment by landryb** [comment]
But yay for seeing this merged \o/

**Comment by giampaolo** [comment]
> as i already said several times, open_files() will never get implemented, the kernel won't provide such an API.

Do you know if this is a kernel bug? We have the same problem on FreeBSD which *does* provide the necessary API but the path sometimes is empty. Also OpenBSD should provide it (`kif->unp_path`) and it's empty. Any internet reference which explains any of this is welcome.

**Comment by giampaolo** [comment]
@landryb  can you please comment about this? https://github.com/giampaolo/psutil/blob/fc1e59d08c968898c2ede425a621b62ccf44681c/psutil/arch/bsd/openbsd.c#L743

**Comment by landryb** [comment]
> Do you know if this is a kernel bug? We have the same problem on FreeBSD which does provide the necessary API but the path sometimes is empty. Also OpenBSD should provide it (kif->unp_path) and it's empty. Any internet reference which explains any of this is welcome.

This is not a bug, it's on purpose for 'privacy reasons'. As for ```kif->unp_path```, it's not filled much, see http://bxr.su/search?q=unp_path&project=OpenBSD

The only information you can get is the inode (see http://www.openbsd.org/cgi-bin/man.cgi/OpenBSD-current/man1/fstat.1 from which you can list open inodes for a process), from which you *could* theoretically do lookups in the filesystem but this is cumbersome.

```
$fstat -p 21801   
USER     CMD          PID   FD MOUNT        INUM MODE       R/W    SZ|DV
landry   xfce4-session 21801 text /         1147672 -r-xr-xr-x   r   189368
landry   xfce4-session 21801   wd /home    29491840 drwxr-xr-x   r     7680
landry   xfce4-session 21801    0 /         1716753 crw-rw-rw-  rw     null
landry   xfce4-session 21801    1 /home    29496358 -rw-r--r--   w   407233
landry   xfce4-session 21801    2 /home    29496358 -rw-r--r--   w   407233
landry   xfce4-session 21801    3 /          572089 -rw-r--r--   w     2643
landry   xfce4-session 21801    4* unix stream 0x0
landry   xfce4-session 21801    5 pipe 0x0 state: 
landry   xfce4-session 21801    6 pipe 0x0 state: 
landry   xfce4-session 21801    7* unix stream 0x0
landry   xfce4-session 21801    8* unix stream 0x0
landry   xfce4-session 21801    9 /home    29492111 -rw-r--r--   w    11834
landry   xfce4-session 21801   10 pipe 0x0 state: 
landry   xfce4-session 21801   11 pipe 0x0 state: 
landry   xfce4-session 21801   12* unix stream 0x0
landry   xfce4-session 21801   13* unix stream 0x0
landry   xfce4-session 21801   14* unix stream 0x0
landry   xfce4-session 21801   15* unix stream 0x0
landry   xfce4-session 21801   16* unix stream 0x0
landry   xfce4-session 21801   17* unix stream 0x0

```

> @landryb can you please comment about this? https://github.com/giampaolo/psutil/blob/fc1e59d08c968898c2ede425a621b62ccf44681c/psutil/arch/bsd/openbsd.c#L743

struct diskstats doesnt provide a breakdown between read and write time i think, see
http://bxr.su/OpenBSD/sys/sys/disk.h#62

**Comment by landryb** [comment]
As for the open files, the OS providing this information have to keep a cache of fd/inode/path around, and update it if the file is moved/hardlinked/etc - OpenBSD just doesnt do this.

**Pull request merged**
