### PR TITLE
make users() include pid into suser tuple

### PR DESCRIPTION
**Pull request by alexanha**
cf. #1022

### CODE REVIEW

**Comment by giampaolo** [comment]
For consistency with the returned Python named tuple could you please always put the PID as the last element of the returned tuple in the C extension?

**Comment by giampaolo** [comment]
...and while you're at it also update HISTORY and CREDITS files.

**Comment by giampaolo** [comment]
Looks good, thanks. Merging.
Just one last thing. How should I describe this field in the doc? What is the PID referring to?

**Comment by alexanha** [comment]
Awsome, thanks.
Concerning the pid: Formally speaking, since ``psutil.users()`` provides an interface to ``utmp`` it is the content of the ``ut_pid`` entry of each login entry in ``utmp`` (cf. ``man utmp``). Practically speaking it is the process id of the login process (like sshd, tmux, gdm-session-worker,...).

When can I expect this change to be released?

**Comment by giampaolo** [comment]
OK, thanks. I updated doc in accordance.
I expect to make a new release pretty soon (days).

**Pull request merged**
