### PR TITLE
[WIP] [Linux] Connections in separate network namespaces are invisible

### PR DESCRIPTION
**Pull request by davereikher**
Please see #1611 for explanation of the problem and related discussion.

### CODE REVIEW

**Comment by davereikher** [comment]
@giampaolo Can you please re-open the pull request if it's possible? I had strange test failures which were unrelated to my code on FreeBSD and I attempted to force-push the master branch into this branch to check if those tests fail there as well, but Github closed the issue saying it was 'merged'...

**Comment by giampaolo** [comment]
Hey there. Not sure what happened but this PR says "davereikher:linux_all_ns was force-pushed and no longer has any new commits.". It looks empty or in sync with current master branch.

**Comment by davereikher** [comment]
I pushed my original branch. Could you please try to re-open again?

**Comment by giampaolo** [comment]
I can't reopen: the "re-open" button is grey. It looks like your branch has no diff/changes with my master anymore (click on "files changed", there's no diff).

**Comment by giampaolo** [comment]
...just open a new PR =)

**Pull request closed without merging**
