### PR TITLE
[Windows] Reset `mp_flag` after each drive on `psutil.disk_partitions()`

### LINKED ISSUE #1598: [Windows] disk_partitions(all=True) only returns mountpoints on drives where it first finds one
**Platform**
* detected on Windows Server 2019 but may not be isolated to that version
* psutil 5.6.3

**Bug description**

Somewhat related to https://github.com/giampaolo/psutil/pull/1192
Above works but once it finds a mountpoint on a drive letter, it will not look for mountpoints on next drive letters.

Example:
Given 3 drive letters, `C:`, `D:`, `Z:`.

- case 1: mountpoints on C, D and Z
  - mount `C:/mnt1/` - detected/returned by psutil
  - mount `C:/mnt2/` - detected/returned by psutil
  - mount `D:/mnt3/` - not returned
  - mount `Z:/mnt4/` - not returned

- case 2: no mount points on C:
  - mounts in `C:/` - none
  - mount `D:/mnt3/` - detected/returned by psutil
  - mount `Z:/mnt4/` - not returned

Expectation is that all mountpoints from all drives are returned.

```
traceback message (if any)
```

```python
import psutil
psutil.disk_partitions(all=True)
```

### PR DESCRIPTION
**Pull request by mx-psi**
## Summary

* OS: Windows
* Bug fix: yes
* Type: core
* Fixes: #1598

## Description

Fixes #1598; before this only the first drive partitions were gathered, since `mp_flag` was never reset to `TRUE`.

Signed-off-by: Pablo Baeyens <pablo.baeyens@datadoghq.com>

### CODE REVIEW

**Comment by mx-psi** [comment]
@giampaolo kindly asking for a review whenever you find the time :)

**Comment by Miao-jh** [comment]
I built and installed the brance fix-mountpoints-issue but this doesn't work on me。
system: Win10 2004 professional
mountpoint: z:\z1, z:\z2 z:\z3

**Comment by Miao-jh** [comment]
[psutil-5.8.1-cp37-cp37m-win_amd64.whl.zip](https://github.com/giampaolo/psutil/files/6806859/psutil-5.8.1-cp37-cp37m-win_amd64.whl.zip)
built wheel

**Comment by mx-psi** [comment]
Hey @Miao-jh thanks for trying this out :) can you give me more details to see if I can reproduce (e.g. what are the other disks? do other disks apart from Z have mountpoints?) ? I am interested to see if you tried this out with administrator privileges, since the mountpoints can be missing because of permissions issues too.

**Comment by mx-psi** [comment]
I am going to mark this as draft until I verify the above

**Comment by mx-psi** [comment]
I did some further tests with this and I am confident that this PR solves the issue. Here is the output of the test on a Windows 10 20H2 machine. I used the "Disk Management" tool to have the following mountpoints:

- For the C: drive
  - `C:\`,
  - `C:\Mountpoints\ExtraC1` and
  - `C:\Mountpoints\ExtraC2`.
- For the D: drive
  - `D:\`,
  - `D:\Mountpoints\ExtraD1` and
  - `D:\Mountpoints\ExtraD2`.

I ran 
```sh
python3 -c "import psutil; import pprint; pprint.pprint(psutil.disk_partitions())"
``` 

with the latest available `psutil` version (version 5.8.0) and with this PR psutil version (commit 57eadeffd639e5546619063696682e8ac7c2b9ca):

<details>
<summary> psutil (version 5.8.0) output</summary>

```
PS> python3 -m pip uninstall -y psutil
WARNING: Skipping psutil as it is not installed.
PS> python3 -m pip install psutil
Collecting psutil
  Using cached psutil-5.8.0-cp37-cp37m-win_amd64.whl (244 kB)
Installing collected packages: psutil
PS> python3 -c "import psutil; import pprint; pprint.pprint(psutil.disk_partitions())"
[sdiskpart(device='C:\\', mountpoint='C:\\Mountpoints\\ExtraC1\\', fstype='NTFS', opts='rw', maxfile=255, maxpath=260),
 sdiskpart(device='C:\\', mountpoint='C:\\Mountpoints\\ExtraC2\\', fstype='NTFS', opts='rw', maxfile=255, maxpath=260),
 sdiskpart(device='C:\\', mountpoint='C:\\', fstype='NTFS', opts='rw,fixed', maxfile=255, maxpath=260),
 sdiskpart(device='D:\\', mountpoint='D:\\', fstype='NTFS', opts='rw,fixed', maxfile=255, maxpath=260)]
```

</details>

<details>
<summary> psutil (version from this branch) output </summary>

```
PS> python3 -m pip uninstall -y psutil
Found existing installation: psutil 5.8.0
Uninstalling psutil-5.8.0:
  Successfully uninstalled psutil-5.8.0
PS> python3 -m pip install git+https://github.com/mx-psi/psutil@57eadeffd639e5546619063696682e8ac7c2b9ca
Collecting git+https://github.com/mx-psi/psutil@57eadeffd639e5546619063696682e8ac7c2b9ca
  Cloning https://github.com/mx-psi/psutil (to revision 57eadeffd639e5546619063696682e8ac7c2b9ca) to c:\users\pablo\appdata\local\temp\pip-req-build-wubt9xm7
  Running command git clone -q https://github.com/mx-psi/psutil 'C:\Users\pablo\AppData\Local\Temp\pip-req-build-wubt9xm7'
  Running command git rev-parse -q --verify 'sha^57eadeffd639e5546619063696682e8ac7c2b9ca'
  Running command git fetch -q https://github.com/mx-psi/psutil 57eadeffd639e5546619063696682e8ac7c2b9ca
  Running command git checkout -q 57eadeffd639e5546619063696682e8ac7c2b9ca
  Resolved https://github.com/mx-psi/psutil to commit 57eadeffd639e5546619063696682e8ac7c2b9ca
Building wheels for collected packages: psutil
  Building wheel for psutil (setup.py) ... done
  Created wheel for psutil: filename=psutil-5.8.1-cp37-cp37m-win_amd64.whl size=247185 sha256=88ee3619374f07fdeb839a3b1f2ad1e1103517564ba03b2699e6856ba99460cb
  Stored in directory: c:\users\pablo\appdata\local\pip\cache\wheels\70\74\13\cd3147ead11afb61f8fbb681b35bfa35596a0198db37584631
Successfully built psutil
Installing collected packages: psutil
Successfully installed psutil-5.8.1
PS> python3 -c "import psutil; import pprint; pprint.pprint(psutil.disk_partitions())"
[sdiskpart(device='C:\\', mountpoint='C:\\Mountpoints\\ExtraC1\\', fstype='NTFS', opts='rw', maxfile=255, maxpath=260),
 sdiskpart(device='C:\\', mountpoint='C:\\Mountpoints\\ExtraC2\\', fstype='NTFS', opts='rw', maxfile=255, maxpath=260),
 sdiskpart(device='C:\\', mountpoint='C:\\', fstype='NTFS', opts='rw,fixed', maxfile=255, maxpath=260),
 sdiskpart(device='D:\\', mountpoint='D:\\Mountpoints\\ExtraD1\\', fstype='NTFS', opts='rw', maxfile=255, maxpath=260),
 sdiskpart(device='D:\\', mountpoint='D:\\Mountpoints\\ExtraD2\\', fstype='NTFS', opts='rw', maxfile=255, maxpath=260),
 sdiskpart(device='D:\\', mountpoint='D:\\', fstype='NTFS', opts='rw,fixed', maxfile=255, maxpath=260)]
```

</details>

As you can see from the Powershell sessions above, the current psutil release does not report the extra `D:` mountpoints, while my patch addresses the issue and lists them on the output.

I am happy to remove the "fixes #1598" line if there are doubts about this PR fixing the issue completely because of @Miao-jh comments above, but I think this would at the very least address the issue on most settings and it would be beneficial to merge.

---

cc @giampaolo kindly asking you to take a look at the above and consider merging this PR :)

**Comment by giampaolo** [comment]
Hey Pablo. I'm not sure I understand the change. You moved:

```
BOOL mp_flag= TRUE;
```

...in the `while` loop some lines below. Isn't it conceptually the same thing? I don't understand why it should make a difference.

**Comment by mx-psi** [comment]
> Hey Pablo. I'm not sure I understand the change. You moved:
> 
> ```
> BOOL mp_flag= TRUE;
> ```
> 
> ...in the `while` loop some lines below. Isn't it conceptually the same thing? I don't understand why it should make a difference.

Right now the `mp_flag` variable is set to `TRUE` just once, **outside** the `while` loop (it is set on line 206 but the loop starts at line 235).  With my change the `mp_flag` is set to `TRUE` inside the loop, so it is set to `TRUE` on each loop iteration (i.e. for each drive letter).

**Comment by giampaolo** [comment]
Oh yes, I understand now (there are multiple drive letters and it can be set to FALSE during the main `while` loop). Can you please just do this (style change):

* leave `BOOL mp_flag = TRUE;` defined at the top of the function
* reset it to TRUE later in the loop: `'mp_flag = TRUE;`, as you're doing now (just without the type definition)

Other than that, LGTM and it's ready to go.

**Comment by mx-psi** [comment]
>  Can you please just do this (style change)

Done! And I tested again with the last commit (51187ba6d5da8467de1391199b53dd050eb7518b) just to be sure:

<details>
<summary>Output</summary>

```
PS C:\Users\pablo> python3 -m pip uninstall -y psutil
Found existing installation: psutil 5.8.1
Uninstalling psutil-5.8.1:
  Successfully uninstalled psutil-5.8.1
PS C:\Users\pablo> python3 -m pip install git+https://github.com/mx-psi/psutil@51187ba6d5da8467de1391199b53dd050eb7518b
Collecting git+https://github.com/mx-psi/psutil@51187ba6d5da8467de1391199b53dd050eb7518b
  Cloning https://github.com/mx-psi/psutil (to revision 51187ba6d5da8467de1391199b53dd050eb7518b) to c:\users\pablo\appdata\local\temp\pip-req-build-vwsji08k
  Running command git clone -q https://github.com/mx-psi/psutil 'C:\Users\pablo\AppData\Local\Temp\pip-req-build-vwsji08k'
  Running command git rev-parse -q --verify 'sha^51187ba6d5da8467de1391199b53dd050eb7518b'
  Running command git fetch -q https://github.com/mx-psi/psutil 51187ba6d5da8467de1391199b53dd050eb7518b
  Running command git checkout -q 51187ba6d5da8467de1391199b53dd050eb7518b
  Resolved https://github.com/mx-psi/psutil to commit 51187ba6d5da8467de1391199b53dd050eb7518b
Building wheels for collected packages: psutil
  Building wheel for psutil (setup.py) ... done
  Created wheel for psutil: filename=psutil-5.8.1-cp37-cp37m-win_amd64.whl size=247182 sha256=d58d8cbd7572316ea605bdc38cf8fb1ad992354965fb33e21118d66bbfd6ac15
  Stored in directory: c:\users\pablo\appdata\local\pip\cache\wheels\a4\fd\96\bd3f5f84d5a8acb328ffd48aeb753e6b7801117b87c24eacdc
Successfully built psutil
Installing collected packages: psutil
Successfully installed psutil-5.8.1
PS C:\Users\pablo> python3 -c "import psutil; import pprint; pprint.pprint(psutil.disk_partitions())"
[sdiskpart(device='C:\\', mountpoint='C:\\Mountpoints\\ExtraC1\\', fstype='NTFS', opts='rw', maxfile=255, maxpath=260),
 sdiskpart(device='C:\\', mountpoint='C:\\Mountpoints\\ExtraC2\\', fstype='NTFS', opts='rw', maxfile=255, maxpath=260),
 sdiskpart(device='C:\\', mountpoint='C:\\', fstype='NTFS', opts='rw,fixed', maxfile=255, maxpath=260),
 sdiskpart(device='D:\\', mountpoint='D:\\Mountpoints\\ExtraD1\\', fstype='NTFS', opts='rw', maxfile=255, maxpath=260),
 sdiskpart(device='D:\\', mountpoint='D:\\Mountpoints\\ExtraD2\\', fstype='NTFS', opts='rw', maxfile=255, maxpath=260),
 sdiskpart(device='D:\\', mountpoint='D:\\', fstype='NTFS', opts='rw,fixed', maxfile=255, maxpath=260)]
```

</details>

**Comment by giampaolo** [comment]
Merged. Thanks Pablo!

**Pull request merged**
