### PR TITLE
Windows: Add mising system DLLs import libraries.

### PR DESCRIPTION
**Pull request by Biswa96**

### CODE REVIEW

**Comment by giampaolo** [comment]
It looks like this breaks python 2.7
https://ci.appveyor.com/project/giampaolo/psutil/builds/35688603/job/q3d29ymct4bwyeou
What problem does this solve? Can you provide an error/traceback?

**Comment by Biswa96** [comment]
This helps to build without using `GetProcAddress` function. The build error in Appveyor seems suspicious. The error is `LINK : fatal error LNK1181: cannot open input file 'ntdll.lib'`. It is related to Visual Studio. But `ntdll.lib` is present in any version of Windows SDK.

**Comment by Biswa96** [comment]
This helps to build without using `GetProcAddress` function (here `psutil_loadlibs`). The build error in Appveyor seems suspicious. The error is `LINK : fatal error LNK1181: cannot open input file 'ntdll.lib'`. It is related to Visual Studio. But `ntdll.lib` is present in any version of Windows SDK.

**Comment by giampaolo** [comment]
What's the problem with `GetProcAddress` / `psutil_loadlibs`?

**Comment by Biswa96** [comment]
While compiling with GCC in Windows, there are may errors about multiple definition at linking time. Probably because many APIs are redefined in `ntexapi.h` file.

**Comment by giampaolo** [comment]
GCC on Windows? Are you trying to compile for cygwin? Because in that case it's not supported.

**Comment by Biswa96** [comment]
It's MSYS2/mingw.

**Comment by giampaolo** [comment]
Also not supported (explicitly, I dropped mingw support years ago because supporting both compilers was a pain + the VS suite for compiling became free). You should use Visual Studio. setup.py could be be made a bit smarter to detect that and recommend VS though.

**Comment by Biswa96** [comment]
> Also not supported

OK, as you wish.

> You should use Visual Studio. 

Visual Studio, the second most bloated IDE after Android Studio.

**Pull request closed without merging**
