### PR TITLE
Refactor win cwd cmdline

### PR DESCRIPTION
**Pull request by fbenkstein**
As discussed this creates a common function for Process.cwd and Process.cwdline on Windows.

### CODE REVIEW

**Comment by giampaolo** [comment]
Appveyor failure: https://ci.appveyor.com/project/giampaolo/psutil/build/367/job/13xvsqt4e09p6i60
```
        path = cext.proc_cwd(self.pid)
    WindowsError: [Error 299] Only part of a ReadProcessMemory or WriteProcessMemory request was completed
 ```

**Comment by fbenkstein** [comment]
Appveyor failure seems unrelated.

**Comment by giampaolo** [comment]
Mmmm are you sure? I don't recall ever seeing that error.

**Comment by fbenkstein** [comment]
The first error was definitely caused by my change.  I made an update and now I'm only seing:

```
ERROR: test_prog_w_funky_name (__main__.TestProcess)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_psutil.py", line 1802, in test_prog_w_funky_name
    self.assertEqual(p.cmdline(), cmdline)
  File "C:\Python27-x64\lib\site-packages\psutil-3.5.0-py2.7-win-amd64.egg\psutil\__init__.py", line 603, in cmdline
    return self._proc.cmdline()
  File "C:\Python27-x64\lib\site-packages\psutil-3.5.0-py2.7-win-amd64.egg\psutil\_pswindows.py", line 290, in wrapper
    raise NoSuchProcess(self.pid, self._name)
NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=1884, name='psuz8b8nufoo bar )')
```

https://ci.appveyor.com/project/giampaolo/psutil/build/370/job/khsp57dfqvvbomj1#L418

**Comment by fbenkstein** [comment]
Seems ready now.

**Comment by giampaolo** [comment]
Can you please update HISTORY.rst describing what has been fixed here?

**Comment by fbenkstein** [comment]
This isn't actually fixing anything it's just shuffling code around and consolidating.  The real fix comes in https://github.com/giampaolo/psutil/pull/739.

**Pull request merged**
