### PR TITLE
add code formatter for c code

### PR DESCRIPTION
**Pull request by fbenkstein**
This adds an uncrustify target which will rewrite all C files.  I tried apply PEP 7 rules and keep the rest mostly as it is.  Might need some tweaking.

### CODE REVIEW

**Comment by giampaolo** [comment]
Thanks for looking into this. There are some style changes I don't agree with but I like this idea. Let me try to experiment with this a little (probably tomorrow).
Also, it would be good to integrate this with the already existent GIT commit hook which now checks edited *.py files with flake8. The same thing should be done for the edited C file and reject the commit if they are not compliant. I wonder whether it exists an `.uncrustify.cfg` for PEP7. I not finding any... which is kinda weird.

**Comment by giampaolo** [comment]
I'm trying to play a bit with uncrustify. What I would like to do is to apply one fix at a time, for instance this:

```
# Try to limit code width to N number of columns
code_width                               = 79        # number
```

...but apparently there's a set of fixes which are applied implicitly by default and I can't disable them.

**Comment by fbenkstein** [comment]
Hm.  I think it should be possible to set almost all fixers to "ignore".

**Comment by giampaolo** [comment]
Kept experimenting. It just seems to hard to configure this the way I want to. I think it's better if we post-pone this for a later time; perhaps by finding a linter which is easier to configure and maintain.

**Comment by fbenkstein** [comment]
Seems reasonable.  I also looked at clang-format but it doesn't look stable
enough to be usable.

**Pull request closed without merging**
